HRPortal/HRPortal.UI/Controllers/Internal/ApplicationController.cs
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Contracts.Manager;
using HRPortal.Models;

namespace HRPortal.UI.Controllers.Internal
{
    public class ApplicationController : Controller
    {
        private readonly IApplicationManager _appMgr;

        public ApplicationController()
        {
            _appMgr = ManagerFactory.GetApplicationManager();
        }

        [HttpPost]
        public ActionResult Edit(int applicationId, Application applicationToEdit)
        {
            Response<Application> response = _appMgr.Edit(applicationId, applicationToEdit);

            return RedirectToAction(response.Success ? "ViewApplications" : "Index", "Hr");
        }

        [HttpPost]
        public ActionResult Remove(int applicationId)
        {
            Response<int> resposne = _appMgr.Remove(applicationId);

            return RedirectToAction(resposne.Success ? "ViewApplications" : "Index", "Hr");
        }
    }
}

HRPortal/HRPortal.UI/Controllers/Internal/CategoryController.cs
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Contracts.Manager;
using HRPortal.Models;

namespace HRPortal.UI.Controllers.Internal
{
    public class CategoryController : Controller
    {
        private readonly ICategoryManager _catMgr;

        public CategoryController()
        {
            _catMgr = ManagerFactory.GetCategoryManager();
        }

        [HttpPost]
        public ActionResult Add(Category categoryToAdd)
        {
            Response<Category> response = _catMgr.Add(categoryToAdd);

            return RedirectToAction(response.Success ? "ManagePolicies" : "Index", "Hr");
        }

        [HttpPost]
        public ActionResult Edit(int categoryId, Category categoryToEdit)
        {
            Response<Category> response = _catMgr.Edit(categoryId, categoryToEdit);

            return RedirectToAction(response.Success ? "ManagePolicies" : "Index", "Hr");
        }

        [HttpPost]
        public ActionResult Remove(int categoryId)
        {
            Response<int> response = _catMgr.Remove(categoryId);

            return RedirectToAction(response.Success ? "ManagePolicies" : "Index", "Hr");
        }
    }
}

HRPortal/HRPortal.UI/Controllers/Internal/HourlyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Contracts.Manager;
using HRPortal.Models;
using HRPortal.UI.Models;

namespace HRPortal.UI.Controllers.Internal
{
    public class HourlyController : Controller
    {
        private readonly ITimeSheetManager _tshMgr;
        private readonly ICategoryManager _catMgr;
        
        public HourlyController()
        {
            _tshMgr = ManagerFactory.GetTimeSheetManager();
            _catMgr = ManagerFactory.GetCategoryManager();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewPolicies()
        {
            Response<List<Category>> response = _catMgr.LoadAll();

            return response.Success
                ? (ActionResult)
                    View(
                        _catMgr.LoadAll()
                            .Data.Select(category => new CategoryWithItsPoliciesVm(category.CategoryId))
                            .ToList())
                : RedirectToAction("Index", "Hourly");
        }

        public ActionResult SubmitTime()
        {
            ViewData["alertDisplay"] = "none";
            ViewData["alertMsg"] = "";
            ViewData["alertType"] = "";
            return View(new TimeSheetEntryVm());
        }

        [HttpPost]
        public ActionResult SubmitTime(TimeSheetEntryVm vm)
        {
            if (!ModelState.IsValid) return View(vm);

            if (_tshMgr.LoadAll()
                    .Data.Select(ts => ts)
                    .Where(ts => ts.EmployeeId == vm.TimeEntry.EmployeeId)
                    .Select(d => d.Date)
                    .Contains(vm.TimeEntry.Date))
            {
                ViewData["alertType"] = "alert-danger";
                ViewData["alertMsg"] = "You have already entered a time sheet for this date.";
                ViewData["alertDisplay"] = "block";
                return View(vm);
            }

            var response = _tshMgr.Add(vm.TimeEntry);

            ViewData["alertType"] = response.Success ? "alert-success" : "alert-danger";
            ViewData["alertMsg"] = response.Message;
            ViewData["alertDisplay"] = "block";

            return View(vm);
        }
    }
}

HRPortal/HRPortal.UI/Controllers/Internal/HrController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Contracts.Manager;
using HRPortal.Models;
using HRPortal.UI.Models;

namespace HRPortal.UI.Controllers.Internal
{
    public class HrController : Controller
    {
        private readonly IApplicationManager _appMgr;
        private readonly ICategoryManager _catMgr;
        private readonly IEmployeeManager _empMgr;

        public HrController()
        {
            _appMgr = ManagerFactory.GetApplicationManager();
            _catMgr = ManagerFactory.GetCategoryManager();
            _empMgr = ManagerFactory.GetEmployeeManager();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewApplications()
        {
            Response<List<Application>> response = _appMgr.LoadAll();

            return response.Success ? View(response.Data) : View("Index");
        }

        public ActionResult ViewPolicies()
        {
            Response<List<Category>> response = _catMgr.LoadAll();

            return response.Success
                ? View(
                    _catMgr.LoadAll()
                        .Data.Select(category => new CategoryWithItsPoliciesVm(category.CategoryId))
                        .ToList())
                : View("Index");
        }

        public ActionResult ManagePolicies()
        {
            Response<List<Category>> response = _catMgr.LoadAll();

            return response.Success
                ? View(
                    _catMgr.LoadAll()
                        .Data.Select(category => new CategoryWithItsPoliciesVm(category.CategoryId))
                        .ToList())
                : View("Index");
        }

        public ActionResult ViewTimeSheets()
        {
            var response = _empMgr.LoadAll();
            var empList = new List<EmployeeAndTimeSheetsVm>();
            
            if (response.Success)
            {
                empList.AddRange(response.Data.Select(employee => new EmployeeAndTimeSheetsVm(employee.EmployeeId)));
            }
            return View(empList);
        }
    }
}

HRPortal/HRPortal.UI/Controllers/Internal/PolicyController.cs
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Contracts.Manager;
using HRPortal.Models;

namespace HRPortal.UI.Controllers.Internal
{
    public class PolicyController : Controller
    {
        private readonly IPolicyManager _polMgr;

        public PolicyController()
        {
            _polMgr = ManagerFactory.GetPolicyManager();
        }

        [HttpPost]
        public ActionResult Add(Policy policyToAdd)
        {
            _polMgr.Add(policyToAdd);

            return RedirectToAction("ManagePolicies", "Hr");
        }

        [HttpPost]
        public ActionResult Edit(int policyId, Policy policyToEdit)
        {
            _polMgr.Edit(policyId, policyToEdit);

            return RedirectToAction("ManagePolicies", "Hr");
        }

        [HttpPost]
        public ActionResult Remove(int policyId)
        {
            _polMgr.Remove(policyId);

            return RedirectToAction("ManagePolicies", "Hr");
        }
    }
}

HRPortal/HRPortal.UI/Controllers/Internal/TimeSheetController.cs
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Contracts.Manager;
using HRPortal.Models;

namespace HRPortal.UI.Controllers.Internal
{
    public class TimeSheetController : Controller
    {
        private readonly ITimeSheetManager _tshMgr;

        public TimeSheetController()
        {
            _tshMgr = ManagerFactory.GetTimeSheetManager();
        }

        [HttpPost]
        public ActionResult Remove(int timeSheetId)
        {
            Response<int> response = _tshMgr.Remove(timeSheetId);

            return RedirectToAction(response.Success ? "ViewTimeSheets" : "Index", "Hr");
        }
    }
}

HRPortal/HRPortal.UI/Controllers/Public/HomeController.cs
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Contracts.Manager;
using HRPortal.Models;

namespace HRPortal.UI.Controllers.Public
{
    public class HomeController : Controller
    {
        private readonly IApplicationManager _mgr;

        public HomeController()
        {
            _mgr = ManagerFactory.GetApplicationManager();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Apply()
        {
            ViewData["alertDisplay"] = "none";
            ViewData["alertMsg"] = "";
            ViewData["alertType"] = "";
            return View();
        }

        [HttpPost]
        public ActionResult Apply(Application applicationToAdd)
        {

            var response = _mgr.Add(applicationToAdd);

            if (response.Success)
            {
                ViewData["alertType"] = "alert-success";
            }
            else
            {
                ViewData["alertType"] = "alert-danger";
            }
            ViewData["alertMsg"] = response.Message;
            ViewData["alertDisplay"] = "block";

            return View();
        }
    }
}

HRPortal/HRPortal.UI/Views/Shared/_Application.cshtml
@model HRPortal.Models.Application

<div class="panel panel-default">
    <div class="panel-heading" id="@($"heading{Model.ApplicationId}")">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#@($"collapse{Model.ApplicationId}")"><strong>@Model.LastName, @Model.FirstName</strong></a>
        </h4>
    </div>
    <div id="@($"collapse{Model.ApplicationId}")" class="panel-collapse collapse">

        <div class="panel-body" style="display: block;" id="@($"displayApplication{Model.ApplicationId}")">

            <label for="@($"displayWhyus{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2">Why Us?</label>
            <div class="col-xs-12 col-sm-4">
                <textarea id="@($"displayWhyus{Model.ApplicationId}")" class="form-control" readonly rows="6">@Model.WhyInterested</textarea>
            </div>

            <label for="@($"displayPhone{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2">Phone #</label>
            <div class="col-xs-12 col-sm-4">
                <input id="@($"displayPhone{Model.ApplicationId}")" class="form-control" value="@Model.Phone" readonly/>
            </div>

            <label for="@($"displayEmail{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2"><a href="@($"mailto:{Model.Email}")" target="_blank">Email</a></label>
            <div class="col-xs-12 col-sm-4">
                <input id="@($"displayEmail{Model.ApplicationId}")" class="form-control" value="@Model.Email" readonly/>
            </div>

            <label for="@($"displayLinkedIn{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2"><a href="@($"{ViewData["LiUrl"]}")" target="_blank">LinkedIn</a></label>
            <div class="col-xs-12 col-sm-4">
                <input id="@($"displayLinkedIn{Model.ApplicationId}")" class="form-control" value="@Model.LinkedIn" readonly/>
            </div>
            <div class="clearfix visible-sm visible-md visible-lg"></div>
            <div class="col-xs-12 col-sm-offset-2">
                <button onclick="toggleEdit('@($"displayApplication{Model.ApplicationId}")', '@($"editApplication{Model.ApplicationId}")');" class="btn btn-default">Edit</button>
            </div>
        </div>

        <div class="panel-body" style="display: none" id="@($"editApplication{Model.ApplicationId}")">
            @using (Html.BeginForm("Edit", "Application"))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ApplicationId)

                <label for="@($"editWhyus{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2">Why Us?</label>
                <div class="col-xs-12 col-sm-4">
                    <textarea id="@($"editWhyus{Model.ApplicationId}")" name="WhyInterested" class="form-control" rows="6">@Model.WhyInterested</textarea>
                </div>

                <label for="@($"editPhone{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2">Phone #</label>
                <div class="col-xs-12 col-sm-4">
                    <input id="@($"editPhone{Model.ApplicationId}")" name="Phone" class="form-control" value="@Model.Phone"/>
                </div>

                <label for="@($"editEmail{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2"><a href="@($"mailto:{Model.Email}")" target="_blank">Email</a></label>
                <div class="col-xs-12 col-sm-4">
                    <input id="@($"editEmail{Model.ApplicationId}")" name="Email" class="form-control" value="@Model.Email"/>
                </div>

                <label for="@($"editLinkedIn{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2"><a href="@($"{ViewData["LiUrl"]}")" target="_blank">LinkedIn</a></label>
                <div class="col-xs-12 col-sm-4">
                    <input id="@($"editLinkedIn{Model.ApplicationId}")" name="LinkedIn" class="form-control" value="@Model.LinkedIn"/>
                </div>

                <div class="clearfix visible-sm visible-md visible-lg"></div>

                <label for="@($"editFirstName{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2">First Name</label>
                <div class="col-xs-12 col-sm-4">
                    <input id="@($"editFirstName{Model.ApplicationId}")" name="FirstName" class="form-control" value="@Model.FirstName"/>
                </div>

                <label for="@($"editLastName{Model.ApplicationId}")" class="control-label col-xs-12 col-sm-2">Last Name</label>
                <div class="col-xs-12 col-sm-4">
                    <input id="@($"editLastName{Model.ApplicationId}")" name="LastName" class="form-control" value="@Model.LastName"/>
                </div>

                <div class="col-xs-12 col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Save</button>
                    <button type="submit" formaction="~/Application/Remove" class="btn btn-default">Remove</button>
                </div>
            }
        </div>
    </div>
</div>

HRPortal/HRPortal.UI/Views/Shared/_Category.cshtml
@using HRPortal.Models
@using HRPortal.UI.Models

@model CategoryWithItsPoliciesVm
@{
    Category category = Model.Category;
    List<Policy> policies = Model.Policies;
}
<div class="panel panel-default">

    @if ((bool)ViewData["manage"])
    {
        <div class="panel-heading" id="@($"heading{category.CategoryId}")">
            @if (category.CategoryId == 0)
            {
                <h2 class="panel-title">
                    <span style="margin: 0 26px 0 25px;"></span>
                    <a data-toggle="collapse" data-parent="#accordion" href="#@($"collapse{category.CategoryId}")">@Model.Category.Title</a>
                </h2>
            }
            else
            {
                <form action="/Category/Edit" method="post" class="form-horizontal">
                    <input name="categoryId" type="hidden" value="@category.CategoryId"/>
                    <input name="categoryToEdit.CategoryId" type="hidden" value="@category.CategoryId" />
                    <div id="@($"displayCat{category.CategoryId}")" style="display: block">
                        <div class="row">
                            <span style="margin: 0 4px;"></span>
                            <button type="submit" style="margin: 4px 0 4px 0;" formaction="~/Category/Remove" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-remove red"></span></button>

                            <button type="button" onclick="toggleEdit('@($"displayCat{category.CategoryId}")', '@($"editCat{category.CategoryId}")');" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>

                            <h2 class="panel-title" style="display: inline;">
                                <a data-toggle="collapse" data-parent="#accordion" href="#@($"collapse{category.CategoryId}")">@Model.Category.Title</a>
                            </h2>
                        </div>
                    </div>
                    <div id="@($"editCat{category.CategoryId}")" style="display: none">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <span class="input-group-btn">
                                                <button type="submit" class="btn btn-default btn-sm" style="margin-right: -1px;"><span class="glyphicon glyphicon-ok green"></span></button>
                                            </span>
                                    <input name="categoryToEdit.Title" class="form-control input-sm" value="@Model.Category.Title"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            }
        </div>

        <div id="@($"collapse{category.CategoryId}")" class="panel-collapse collapse">
            <div class="panel-body">

                


                @foreach (var policy in policies)
                {
                    @Html.Partial("_Policy", policy)
                }
            </div>
        </div>

    }
    else
    {
        <div class="panel-heading" id="@($"heading{category.CategoryId}")">
            <h2 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#@($"collapse{category.CategoryId}")">@Model.Category.Title</a>
            </h2>
        </div>
        <div id="@($"collapse{category.CategoryId}")" class="panel-collapse collapse" role="tabpanel">
            <div class="panel-body">
                @foreach (var policy in policies)
                {
                    @Html.Partial("_Policy", policy)
                }
            </div>
        </div>
    }
</div>

HRPortal/HRPortal.UI/Views/Shared/_Employee.cshtml
@model HRPortal.UI.Models.EmployeeAndTimeSheetsVm

<div class="panel panel-default">
    <div class="panel-heading" id="@($"heading{Model.Employee.EmployeeId}")">
        <h2 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#@($"collapse{Model.Employee.EmployeeId}")">@($"{Model.Employee.LastName}, {Model.Employee.FirstName}")</a>
        </h2>
    </div>
    <div class="panel-collapse collapse" id="@($"collapse{Model.Employee.EmployeeId}")">
        <div class="panel-body">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="col-xs-12">
                        <h4>EMPLOYEE SUMMARY</h4>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        Employee ID: @Model.Employee.EmployeeId
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        Hire Date: @Model.Employee.DateHired.ToString("d")
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        Total Hours To Date: @Model.TimeSheets.Select(h => h.HoursWorked).Sum()
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th class="col-xs-1 col-sm-1"></th>
                    <th class="col-xs-1 col-sm-2">DATE</th>
                    <th class="col-xs-10 col-sm-3">HOURS WORKED</th>
                    <th class="col-xs-12 col-sm-6"></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var timeSheet in Model.TimeSheets)
                {
                    @Html.Partial("_TimeSheet", timeSheet)
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

HRPortal/HRPortal.UI/Views/Shared/_Hourly.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SGI Ltd. - Employee Services - @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href='https://fonts.googleapis.com/css?family=Alfa+Slab+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oswald|Cinzel' rel='stylesheet' type='text/css'>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Services", "Index", "Hourly", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracker<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="~/Hourly/SubmitTime">Submit Time</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="~/Hourly/ViewPolicies">View Policies</a></li>
                            @*<li role="separator" class="divider"></li>*@
                            @*<li><a href="~/Hr/ManagePolicies">Manage Policies</a></li>*@
                        </ul>
                    </li>
                    <li>@Html.ActionLink("HR", "Index", "Hr")</li>
                   <li>@Html.ActionLink("Public", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer>
            <div class="welcomefoot">
                <p class="text-center">&copy; @DateTime.Now.Year SG Industries Ltd.</p>
                <p class="text-center">"You get hurt, hurt 'em back. You get killed... walk it off. - Steve Rogers</p>
            </div>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>

HRPortal/HRPortal.UI/Views/Shared/_Internal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SGI Ltd. - HR Portal - @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href='https://fonts.googleapis.com/css?family=Alfa+Slab+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oswald|Cinzel' rel='stylesheet' type='text/css'>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HR Portal", "Index", "Hr", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Applications<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="~/Hr/ViewApplications">View Applications</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="~/Hr/ViewPolicies">View Policies</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="~/Hr/ManagePolicies">Manage Policies</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracker<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="~/Hr/ViewTimeSheets">View Timesheets</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Employee", "Index", "Hourly")</li>
                    <li>@Html.ActionLink("Public", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer>
            <div class="welcomefoot">
                <p class="text-center">&copy; @DateTime.Now.Year SG Industries Ltd.</p>
                <p class="text-center">"Maybe I am a monster. I don't think I'd know if I were one. I'm not what you are and not what you intended." - Vision</p>
            </div>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>

HRPortal/HRPortal.UI/Views/Shared/_Public.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SGI Ltd. - @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href='https://fonts.googleapis.com/css?family=Alfa+Slab+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oswald|Cinzel' rel='stylesheet' type='text/css'>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("SG Industries Ltd.", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Apply", "Apply", "Home")</li>
                        <li>@Html.ActionLink("HR", "Index", "Hr")</li>
                        <li>@Html.ActionLink("Employee", "Index", "Hourly")</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <div class="welcomefoot">
                    <p class="text-center">&copy; @DateTime.Now.Year SG Industries Ltd.</p>
                    <p class="text-center">"Commencing automated assembly. Estimated completion time is five hours." - Jarvis</p>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

HRPortal/HRPortal.UI/Views/Shared/_TimeSheet.cshtml
@model HRPortal.Models.TimeSheet

<tr>
    <td class="col-xs-1 col-sm-1">
        <form action="~/TimeSheet/Remove" method="post" class="form-horizontal">
            <input name="TimeSheetId" type="hidden" value="@Model.TimeSheetId" />
            <button type="submit" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-remove red"></span></button>
        </form>
    </td>
    <td class="col-xs-1 col-sm-2">
        @Model.Date.ToString("d")
    </td>
    <td class="col-xs-10 col-sm-3">
        @Model.HoursWorked
    </td>
    <td class="col-xs-12 col-sm-6"></td>
</tr>